from playsound import playsound
import smtplib
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
import pymysql
import sys

class Ui_fbooking(object):
    def __init__(self,val1,val2):
        self.vv= val1
        self.Gender = ""
        self.datee=""
        self.a=0
        self.Name = ""
        self.Address = ""
        self.Contact = ""
        self.Adhar = ""
        self.CarN = ""
        self.CarM = ""
        self.CarC = ""
        self.username=val2
        self.Time='10am'
        self.Slotno=""
        self.Bookingid=""
        self.CarB=""
        self.mail="xyz@gmail.com"

#SLOT CHECK
    def ss(self):
        if self.a!=0:
            self.label_15.setText(self.Slotno)
            self.label_17.setText(self.Adhar)
            self.label_16.setText(self.CarB)
            self.stackedWidget.setCurrentIndex(3)
        else:
            self.warning("Alert","Slot not selected")
#INSERT BOOKING DETAILS
    def insert(self):
        conn = pymysql.connect(host="localhost", user="root", port=3306, password="123456", db="customer")
        cur = conn.cursor()
        query = "insert into bookingdetails(username,Name,Address,Gender,Contact,Adharcard,CarNo,CarBrand,CarModel,Carcolour,Date,Time,Slotno)values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"
        data = cur.execute(query, (self.username,self.Name,self.Address,self.Gender,self.Contact,self.Adhar,self.CarN,self.CarB,self.CarM,self.CarC,self.datee,self.Time,self.Slotno))
        conn.commit()
        if (data):
            query = "select Bookingid from bookingdetails where username=%s"
            cur.execute(query, (self.username))
            data1= cur.fetchall()
            self.Bookingid=str(data1[0][0])
            self.messagebox("congrats", "successful")

            self.pushBtn_9.setEnabled(False)
            self.pushBtn_10.setEnabled(False)
            self.pushBtn_1.setEnabled(False)
            self.label_18.setText(self.Bookingid)

#SEND BOOKING MAIL
            d = smtplib.SMTP('smtp.gmail.com', 587)
            d.starttls()
            d.login("carparking@gmail.com", "123456789")
            message1 = f"ThankYou '{self.username}'\nYour Bookind-id is: '{self.Bookingid}'\nSlot-Number is: '{self.Slotno}'\nOn Date : '{self.datee}'"
            d.sendmail("carparking@gmail.com", self.vv, message1)
            d.quit()
#UNCOLOR BUTTONS
    def uncolor(self):
        self.pushButton_1.setStyleSheet("background-color: ")
        self.pushButton_2.setStyleSheet("background-color: ")
        self.pushButton_3.setStyleSheet("background-color: ")
        self.pushButton_4.setStyleSheet("background-color: ")
        self.pushButton_5.setStyleSheet("background-color: ")
        self.pushButton_6.setStyleSheet("background-color: ")
        self.pushButton_7.setStyleSheet("background-color: ")
        self.pushButton_8.setStyleSheet("background-color: ")
        self.pushButton_9.setStyleSheet("background-color: ")
        self.pushButton_10.setStyleSheet("background-color: ")
        self.pushButton_11.setStyleSheet("background-color: ")
        self.pushButton_12.setStyleSheet("background-color: ")
        self.pushButton_13.setStyleSheet("background-color: ")
        self.pushButton_14.setStyleSheet("background-color: ")
        self.pushButton_15.setStyleSheet("background-color: ")
        #Enable all
        self.pushButton_1.setEnabled(True)
        self.pushButton_2.setEnabled(True)
        self.pushButton_3.setEnabled(True)
        self.pushButton_4.setEnabled(True)
        self.pushButton_5.setEnabled(True)
        self.pushButton_6.setEnabled(True)
        self.pushButton_7.setEnabled(True)
        self.pushButton_8.setEnabled(True)
        self.pushButton_9.setEnabled(True)
        self.pushButton_10.setEnabled(True)
        self.pushButton_11.setEnabled(True)
        self.pushButton_12.setEnabled(True)
        self.pushButton_13.setEnabled(True)
        self.pushButton_14.setEnabled(True)
        self.pushButton_15.setEnabled(True)
        self.stackedWidget.setCurrentIndex(1)

#SLOT SELECTION(GREEN COLOR)
    def slotselect(self,value):
        if value==1:
            self.pushButton_1.setStyleSheet("background-color: green")
            self.a = 1
            self.Slotno='a1'
        else:
            self.pushButton_1.setStyleSheet("background-color: ")
        if value==2:
            self.pushButton_2.setStyleSheet("background-color: green ")
            self.a = 2
            self.Slotno = 'b1'
        else:
            self.pushButton_2.setStyleSheet("background-color: ")
        if value==3:
            self.pushButton_3.setStyleSheet("background-color: green")
            self.a=3
            self.Slotno = 'c1'
        else:
            self.pushButton_3.setStyleSheet("background-color: ")
        if value==4:
            self.pushButton_4.setStyleSheet("background-color: green")
            self.a=4
            self.Slotno = 'a2'
        else:
            self.pushButton_4.setStyleSheet("background-color: ")
        if value==5:
            self.pushButton_5.setStyleSheet("background-color: green")
            self.a=5
            self.Slotno = 'b2'
        else:
            self.pushButton_5.setStyleSheet("background-color: ")
        if value == 6:
            self.pushButton_6.setStyleSheet("background-color: green")
            self.a = 6
            self.Slotno = 'c2'
        else:
            self.pushButton_6.setStyleSheet("background-color: ")
        if value == 7:
            self.pushButton_7.setStyleSheet("background-color: green")
            self.a = 7
            self.Slotno = 'a3'
        else:
            self.pushButton_7.setStyleSheet("background-color: ")
        if value == 8:
            self.pushButton_8.setStyleSheet("background-color: green")
            self.a = 8
            self.Slotno = 'b3'
        else:
            self.pushButton_8.setStyleSheet("background-color: ")
        if value == 9:
            self.pushButton_9.setStyleSheet("background-color: green")
            self.a = 9
            self.Slotno = 'c3'
        else:
            self.pushButton_9.setStyleSheet("background-color: ")
        if value == 10:
            self.pushButton_10.setStyleSheet("background-color: green")
            self.a = 10
            self.Slotno = 'a4'
        else:
            self.pushButton_10.setStyleSheet("background-color: ")
        if value == 11:
            self.pushButton_11.setStyleSheet("background-color: green")
            self.a = 11
            self.Slotno = 'b4'
        else:
            self.pushButton_11.setStyleSheet("background-color: ")
        if value == 12:
            self.pushButton_12.setStyleSheet("background-color: green")
            self.a = 12
            self.Slotno = 'c4'
        else:
            self.pushButton_12.setStyleSheet("background-color: ")
        if value == 13:
            self.pushButton_13.setStyleSheet("background-color: green")
            self.a = 13
            self.Slotno = 'a5'
        else:
            self.pushButton_13.setStyleSheet("background-color: ")
        if value == 14:
            self.pushButton_14.setStyleSheet("background-color: green")
            self.a = 14
            self.Slotno = 'b5'
        else:
            self.pushButton_14.setStyleSheet("background-color: ")
        if value == 15:
            self.pushButton_15.setStyleSheet("background-color: green")
            self.a = 15
            self.Slotno = 'c5'
        else:
            self.pushButton_15.setStyleSheet("background-color: ")
#DISABLE BOOKED SLOTS
    def disable(self):
        conn = pymysql.connect(host="localhost", user="root", password="123456", db="customer")
        cur = conn.cursor()
        query = "select Slotno from bookingdetails where Date=%s"
        cur.execute(query, (self.datee))
        data=cur.fetchall()
        print(data)
        for row in data:
            if row[0]=="a1":
                self.pushButton_1.setEnabled(False)
            if row[0]=="b1":
                self.pushButton_2.setEnabled(False)
            if row[0]=="c1":
                self.pushButton_3.setEnabled(False)
            if row[0] == "a2":
                self.pushButton_4.setEnabled(False)
            if row[0] == "b2":
                self.pushButton_5.setEnabled(False)
            if row[0] == "c2":
                self.pushButton_6.setEnabled(False)
            if row[0] == "a3":
                self.pushButton_7.setEnabled(False)
            if row[0] == "b3":
                self.pushButton_8.setEnabled(False)
            if row[0] == "c3":
                self.pushButton_9.setEnabled(False)
            if row[0] == "a4":
                self.pushButton_10.setEnabled(False)
            if row[0] == "b4":
                self.pushButton_11.setEnabled(False)
            if row[0] == "c4":
                self.pushButton_12.setEnabled(False)
            if row[0] == "a5":
                self.pushButton_13.setEnabled(False)
            if row[0] == "b5":
                self.pushButton_14.setEnabled(False)
            if row[0] == "c5":
                self.pushButton_15.setEnabled(False)
        '''
        if self.a == 1:
            self.pushButton.setEnabled(False)

        elif self.a == 2:
            self.pushButton_2.setEnabled(False)
        elif self.a == 3:
            self.pushButton_3.setEnabled(False)
        elif self.a == 4:
            self.pushButton_4.setEnabled(False)
        elif self.a == 5:
            self.pushButton_5.setEnabled(False)
        elif self.a == 6:
            self.pushButton_6.setEnabled(False)
        elif self.a == 7:
            self.pushButton_7.setEnabled(False)
        elif self.a == 8:
            self.pushButton_8.setEnabled(False)
        elif self.a == 9:
            self.pushButton_9.setEnabled(False)
        elif self.a == 10:
            self.pushButton_10.setEnabled(False)
        elif self.a == 11:
            self.pushButton_11.setEnabled(False)
        elif self.a == 12:
            self.pushButton_12.setEnabled(False)
        elif self.a == 13:
            self.pushButton_13.setEnabled(False)
        elif self.a == 14:
            self.pushButton_14.setEnabled(False)
        elif self.a == 15:
            self.pushButton_15.setEnabled(False)
       '''
#FETCHING DATE FROM QCALENDAR
    def getdate(self):
        da=str(self.calendarWidget.selectedDate())
        self.datee= da[19:-1]
        self.disable()
        self.stackedWidget.setCurrentIndex(2)
#TAKES USERVALUE
    def registervalue(self):
        self.Name = self.lineEdit.text()
        self.Address = self.textEdit_2.toPlainText()
        self.Contact = self.lineEdit_2.text()
        self.Adhar = self.lineEdit_3.text()
        self.CarN = self.lineEdit_4.text()
        self.CarM = self.lineEdit_6.text()
        self.CarC = self.lineEdit_7.text()
        self.CarB = str(self.comboBox_2.currentText())
        self.label_19.setText(self.username)
        self.label_14.setText(self.CarN)
#FOR MALE-FEMALE
        if self.radioButton.isChecked():
            self.Gender = 'Male'
        elif self.radioButton_2.isChecked():
            self.Gender = 'Female'
        if((self.Gender=="Male" or self.Gender=="Female")and (self.Name!="" and self.Address!="" and self.Contact!="" and self.Adhar!="" and self.CarN != "" and self.CarM != "" and self.CarC!="" and self.CarB!="")):
            self.stackedWidget.setCurrentIndex(1)
        else:
            self.warning("Alert!", "FIELDS CANNOT BE EMPTY!.")

#SHOWING SUCCESSFUL MESSAGE
    def messagebox(self, title, message):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()
        playsound('C:/Users/ritvij/Desktop/hello5.mp3')
#SHOWING WARNING MESSAGE
    def warning(self, title, message):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()

    def cl1(self):
        pass
#MAIN FUNCTION
    def setupUi(self, fbooking):
        fbooking.setObjectName("fbooking")
        fbooking.setEnabled(True)
        fbooking.resize(751, 440)
        self.centralwidget = QtWidgets.QWidget(fbooking)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 20, 751, 421))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_47 = QtWidgets.QLabel(self.page_4)
        self.label_47.setGeometry(QtCore.QRect(240, 0, 331, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_47.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.page_4)
        self.label_48.setGeometry(QtCore.QRect(420, 50, 101, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 56, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 56, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 56, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.label_48.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.label_48.setFont(font)
        self.label_48.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.page_4)
        self.label_49.setGeometry(QtCore.QRect(10, 110, 151, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_49.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.lineEdit = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit.setGeometry(QtCore.QRect(200, 50, 201, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.page_4)
        self.textEdit_2.setGeometry(QtCore.QRect(200, 100, 261, 41))
        self.textEdit_2.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_50 = QtWidgets.QLabel(self.page_4)
        self.label_50.setGeometry(QtCore.QRect(10, 50, 151, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 56, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 56, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 56, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.label_50.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.label_50.setFont(font)
        self.label_50.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_50.setObjectName("label_50")
        self.radioButton = QtWidgets.QRadioButton(self.page_4)
        self.radioButton.setGeometry(QtCore.QRect(530, 50, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.page_4)
        self.radioButton_2.setGeometry(QtCore.QRect(620, 50, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setCheckable(True)
        self.radioButton_2.setChecked(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_51 = QtWidgets.QLabel(self.page_4)
        self.label_51.setGeometry(QtCore.QRect(360, 170, 191, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_51.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_4.setGeometry(QtCore.QRect(200, 230, 131, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_52 = QtWidgets.QLabel(self.page_4)
        self.label_52.setGeometry(QtCore.QRect(360, 290, 151, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_52.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.page_4)
        self.label_53.setGeometry(QtCore.QRect(360, 230, 151, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_53.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_6.setGeometry(QtCore.QRect(200, 290, 131, 21))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_54 = QtWidgets.QLabel(self.page_4)
        self.label_54.setGeometry(QtCore.QRect(10, 170, 151, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_54.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(560, 170, 131, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.LinkVisited, brush)
        self.lineEdit_3.setPalette(palette)
        self.lineEdit_3.setAutoFillBackground(False)
        self.lineEdit_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setPlaceholderText("")
        self.lineEdit_3.setClearButtonEnabled(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_55 = QtWidgets.QLabel(self.page_4)
        self.label_55.setGeometry(QtCore.QRect(10, 230, 131, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_55.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.page_4)
        self.label_56.setGeometry(QtCore.QRect(10, 290, 151, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_56.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 170, 131, 21))
        self.lineEdit_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(560, 290, 131, 21))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.comboBox_2 = QtWidgets.QComboBox(self.page_4)
        self.comboBox_2.setGeometry(QtCore.QRect(560, 230, 131, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.page_4)
        self.pushButton.setGeometry(QtCore.QRect(290, 360, 171, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.registervalue)
        self.label = QtWidgets.QLabel(self.page_4)
        self.label.setGeometry(QtCore.QRect(0, 0, 751, 421))
        self.label.setText("")
        self.label.setPixmap(QPixmap("blue1.png"))
        self.label.setObjectName("label")
        self.label.raise_()
        self.label_47.raise_()
        self.label_48.raise_()
        self.label_49.raise_()
        self.lineEdit.raise_()
        self.textEdit_2.raise_()
        self.label_50.raise_()
        self.radioButton.raise_()
        self.radioButton_2.raise_()
        self.label_51.raise_()
        self.lineEdit_4.raise_()
        self.label_52.raise_()
        self.label_53.raise_()
        self.lineEdit_6.raise_()
        self.label_54.raise_()
        self.lineEdit_3.raise_()
        self.label_55.raise_()
        self.label_56.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_7.raise_()
        self.comboBox_2.raise_()
        self.pushButton.raise_()
        self.stackedWidget.addWidget(self.page_4)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(510, 220, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.page)
        self.calendarWidget.setGeometry(QtCore.QRect(90, 130, 281, 191))
        self.calendarWidget.setMinimumDate(QtCore.QDate.currentDate())

        self.calendarWidget.setObjectName("calendarWidget")
        self.comboBox = QtWidgets.QComboBox(self.page)
        self.comboBox.setGeometry(QtCore.QRect(510, 260, 121, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushBtn_6 = QtWidgets.QPushButton(self.page)
        self.pushBtn_6.setGeometry(QtCore.QRect(310, 350, 131, 51))
        self.pushBtn_6.setObjectName("pushBtn_6")
        self.pushBtn_6.clicked.connect(self.getdate)
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(250, 50, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(100, 110, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.timeEdit = QtWidgets.QTimeEdit(self.page)
        self.timeEdit.setGeometry(QtCore.QRect(510, 170, 121, 21))
        self.timeEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.timeEdit.setMaximumTime(QtCore.QTime(19, 0, 0))
        self.timeEdit.setMinimumTime(QtCore.QTime(6, 0, 0))
        self.timeEdit.setCurrentSection(QtWidgets.QDateTimeEdit.AmPmSection)
        self.timeEdit.setCalendarPopup(False)
        self.timeEdit.setObjectName("timeEdit")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(510, 130, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_57 = QtWidgets.QLabel(self.page)
        self.label_57.setGeometry(QtCore.QRect(0, 0, 751, 421))
        self.label_57.setText("")
        self.label_57.setPixmap(QPixmap("blue1.png"))
        self.label_57.setObjectName("label_57")
        self.pushBtn_12 = QtWidgets.QPushButton(self.page)
        self.pushBtn_12.setGeometry(QtCore.QRect(670, 0, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.pushBtn_12.setFont(font)
        self.pushBtn_12.setObjectName("pushBtn_12")
        self.pushBtn_12.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(0))
        self.label_57.raise_()
        self.label_5.raise_()
        self.calendarWidget.raise_()
        self.comboBox.raise_()
        self.pushBtn_6.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.timeEdit.raise_()
        self.label_4.raise_()
        self.pushBtn_12.raise_()
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_4.setGeometry(QtCore.QRect(230, 180, 71, 21))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(lambda: self.slotselect(4))
        self.pushButton_8 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_8.setGeometry(QtCore.QRect(330, 210, 71, 21))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.clicked.connect(lambda: self.slotselect(8))
        self.pushButton_2 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 150, 71, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(lambda: self.slotselect(2))
        self.pushButton_1 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_1.setGeometry(QtCore.QRect(230, 150, 71, 21))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_1.clicked.connect(lambda: self.slotselect(1))
        self.pushButton_14 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_14.setGeometry(QtCore.QRect(330, 270, 71, 21))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_14.clicked.connect(lambda: self.slotselect(14))
        self.pushButton_12 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_12.setGeometry(QtCore.QRect(430, 240, 71, 21))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_12.clicked.connect(lambda: self.slotselect(12))
        self.label_20 = QtWidgets.QLabel(self.page_2)
        self.label_20.setGeometry(QtCore.QRect(220, 70, 321, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_20.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_5.setGeometry(QtCore.QRect(330, 180, 71, 21))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(lambda: self.slotselect(5))
        self.pushButton_13 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_13.setGeometry(QtCore.QRect(230, 270, 71, 21))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_13.clicked.connect(lambda: self.slotselect(13))
        self.pushBtn_7 = QtWidgets.QPushButton(self.page_2)
        self.pushBtn_7.setGeometry(QtCore.QRect(670, 0, 81, 41))

        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.pushBtn_7.setFont(font)
        self.pushBtn_7.setObjectName("pushBtn_7")
        self.pushBtn_7.clicked.connect(self.uncolor)
        self.pushButton_15 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_15.setGeometry(QtCore.QRect(430, 270, 71, 21))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_15.clicked.connect(lambda: self.slotselect(15))
        self.pushButton_7 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_7.setGeometry(QtCore.QRect(230, 210, 71, 21))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.clicked.connect(lambda: self.slotselect(7))
        self.pushButton_11 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_11.setGeometry(QtCore.QRect(330, 240, 71, 21))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_11.clicked.connect(lambda: self.slotselect(11))
        self.pushButton_10 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_10.setGeometry(QtCore.QRect(230, 240, 71, 21))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.clicked.connect(lambda: self.slotselect(10))
        self.pushBtn_8 = QtWidgets.QPushButton(self.page_2)
        self.pushBtn_8.setEnabled(True)
        self.pushBtn_8.setGeometry(QtCore.QRect(300, 330, 131, 61))
        self.pushBtn_8.setObjectName("pushBtn_8")
        self.pushBtn_8.clicked.connect(self.ss)
        self.pushButton_9 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_9.setGeometry(QtCore.QRect(430, 210, 71, 21))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_9.clicked.connect(lambda: self.slotselect(9))
        self.pushButton_3 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_3.setGeometry(QtCore.QRect(430, 150, 71, 21))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(lambda: self.slotselect(3))

        self.pushButton_6 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_6.setGeometry(QtCore.QRect(430, 180, 71, 21))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(lambda: self.slotselect(6))
        self.label_58 = QtWidgets.QLabel(self.page_2)
        self.label_58.setGeometry(QtCore.QRect(0, 0, 751, 421))
        self.label_58.setText("")
        self.label_58.setPixmap(QPixmap("blue1.png"))
        self.label_58.setObjectName("label_58")
        self.label_58.raise_()
        self.pushButton_4.raise_()
        self.pushButton_8.raise_()
        self.pushButton_2.raise_()
        self.pushButton_1.raise_()
        self.pushButton_14.raise_()
        self.pushButton_12.raise_()
        self.label_20.raise_()
        self.pushButton_5.raise_()
        self.pushButton_13.raise_()
        self.pushBtn_7.raise_()
        self.pushButton_15.raise_()
        self.pushButton_7.raise_()
        self.pushButton_11.raise_()
        self.pushButton_10.raise_()
        self.pushBtn_8.raise_()
        self.pushButton_9.raise_()
        self.pushButton_3.raise_()
        self.pushButton_6.raise_()
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 751, 441))
        self.label_6.setText("")
        self.label_6.setPixmap(QPixmap("blue1.png"))
        self.label_6.setObjectName("label_6")
        self.label_12 = QtWidgets.QLabel(self.page_3)
        self.label_12.setGeometry(QtCore.QRect(30, 340, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_16 = QtWidgets.QLabel(self.page_3)
        self.label_16.setGeometry(QtCore.QRect(200, 190, 141, 21))
        self.label_16.setObjectName("label_16")
        self.label_7 = QtWidgets.QLabel(self.page_3)
        self.label_7.setGeometry(QtCore.QRect(30, 90, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.page_3)
        self.label_9.setGeometry(QtCore.QRect(30, 190, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.pushBtn_9 = QtWidgets.QPushButton(self.page_3)
        self.pushBtn_9.setGeometry(QtCore.QRect(570, 170, 111, 41))
        self.pushBtn_9.setObjectName("pushBtn_9")
        self.pushBtn_9.clicked.connect(self.insert)

        self.label_13 = QtWidgets.QLabel(self.page_3)
        self.label_13.setGeometry(QtCore.QRect(200, 290, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_19 = QtWidgets.QLabel(self.page_3)
        self.label_19.setGeometry(QtCore.QRect(350, 40, 141, 21))
        self.label_19.setObjectName("label_19")
        self.label_18 = QtWidgets.QLabel(self.page_3)
        self.label_18.setGeometry(QtCore.QRect(200, 340, 141, 21))
        self.label_18.setObjectName("label_18")
        self.label_15 = QtWidgets.QLabel(self.page_3)
        self.label_15.setGeometry(QtCore.QRect(200, 140, 141, 21))
        self.label_15.setObjectName("label_15")
        self.label_10 = QtWidgets.QLabel(self.page_3)
        self.label_10.setGeometry(QtCore.QRect(30, 240, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_8 = QtWidgets.QLabel(self.page_3)
        self.label_8.setGeometry(QtCore.QRect(200, 40, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_17 = QtWidgets.QLabel(self.page_3)
        self.label_17.setGeometry(QtCore.QRect(200, 240, 141, 21))
        self.label_17.setObjectName("label_17")
        self.label_11 = QtWidgets.QLabel(self.page_3)
        self.label_11.setGeometry(QtCore.QRect(30, 290, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_14 = QtWidgets.QLabel(self.page_3)
        self.label_14.setGeometry(QtCore.QRect(200, 90, 141, 21))
        self.label_14.setObjectName("label_14")
        self.pushBtn_10 = QtWidgets.QPushButton(self.page_3)
        self.pushBtn_10.setGeometry(QtCore.QRect(670, 0, 81, 41))
        self.pushBtn_10.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(2))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.pushBtn_10.setFont(font)
        self.pushBtn_10.setObjectName("pushBtn_10")
        self.label_21 = QtWidgets.QLabel(self.page_3)
        self.label_21.setGeometry(QtCore.QRect(30, 140, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.stackedWidget.addWidget(self.page_3)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_22 = QtWidgets.QLabel(self.page_6)
        self.label_22.setGeometry(QtCore.QRect(0, 0, 751, 441))
        self.label_22.setText("")
        self.label_22.setPixmap(QPixmap("blue1.png"))
        self.label_22.setObjectName("label_22")
        self.label_25 = QtWidgets.QLabel(self.page_6)
        self.label_25.setGeometry(QtCore.QRect(40, 150, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.page_6)
        self.label_26.setGeometry(QtCore.QRect(40, 300, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.page_6)
        self.label_27.setGeometry(QtCore.QRect(210, 350, 141, 21))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.page_6)
        self.label_28.setGeometry(QtCore.QRect(210, 250, 141, 21))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.page_6)
        self.label_29.setGeometry(QtCore.QRect(210, 50, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.page_6)
        self.label_30.setGeometry(QtCore.QRect(40, 200, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.page_6)
        self.label_31.setGeometry(QtCore.QRect(210, 100, 141, 21))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.page_6)
        self.label_32.setGeometry(QtCore.QRect(210, 150, 141, 21))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.page_6)
        self.label_33.setGeometry(QtCore.QRect(210, 200, 141, 21))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.page_6)
        self.label_34.setGeometry(QtCore.QRect(40, 350, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.page_6)
        self.label_35.setGeometry(QtCore.QRect(360, 50, 141, 21))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.page_6)
        self.label_36.setGeometry(QtCore.QRect(40, 100, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.page_6)
        self.label_37.setGeometry(QtCore.QRect(40, 250, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.page_6)
        self.label_38.setGeometry(QtCore.QRect(210, 300, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.page_6)
        self.label_39.setGeometry(QtCore.QRect(550, 200, 141, 21))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.page_6)
        self.label_40.setGeometry(QtCore.QRect(350, 200, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.label_41 = QtWidgets.QLabel(self.page_7)
        self.label_41.setGeometry(QtCore.QRect(40, 160, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.textEdit = QtWidgets.QTextEdit(self.page_7)
        self.textEdit.setGeometry(QtCore.QRect(220, 160, 441, 201))
        self.textEdit.setObjectName("textEdit")
        self.label_23 = QtWidgets.QLabel(self.page_7)
        self.label_23.setGeometry(QtCore.QRect(40, 40, 531, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_42 = QtWidgets.QLabel(self.page_7)
        self.label_42.setGeometry(QtCore.QRect(40, 100, 521, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.pushBtn_11 = QtWidgets.QPushButton(self.page_7)
        self.pushBtn_11.setGeometry(QtCore.QRect(320, 380, 121, 31))
        self.pushBtn_11.setObjectName("pushBtn_11")
        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.label_24 = QtWidgets.QLabel(self.page_8)
        self.label_24.setGeometry(QtCore.QRect(0, 0, 751, 441))
        self.label_24.setText("")
        self.label_24.setPixmap(QPixmap("blue1.png"))
        self.label_24.setObjectName("label_24")
        self.label_43 = QtWidgets.QLabel(self.page_8)
        self.label_43.setGeometry(QtCore.QRect(40, 150, 521, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.page_8)
        self.label_44.setGeometry(QtCore.QRect(40, 310, 521, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.page_8)
        self.label_45.setGeometry(QtCore.QRect(40, 230, 521, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.page_8)
        self.label_46.setGeometry(QtCore.QRect(40, 60, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.stackedWidget.addWidget(self.page_8)
        self.pushBtn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushBtn_1.setEnabled(True)
        self.pushBtn_1.setGeometry(QtCore.QRect(0, 0, 75, 23))
        self.pushBtn_1.setObjectName("pushBtn_1")
        self.pushBtn_1.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(0))
        self.pushBtn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushBtn_3.setGeometry(QtCore.QRect(140, 0, 75, 23))
        self.pushBtn_3.setObjectName("pushBtn_3")
        self.pushBtn_3.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(5))
        self.pushBtn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushBtn_4.setGeometry(QtCore.QRect(210, 0, 75, 23))
        self.pushBtn_4.setObjectName("pushBtn_4")
        self.pushBtn_4.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(6))
        self.pushBtn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushBtn_5.setGeometry(QtCore.QRect(280, 0, 75, 23))
        self.pushBtn_5.setObjectName("pushBtn_5")
        self.pushBtn_5.clicked.connect(self.cl1)
        self.pushBtn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushBtn_2.setGeometry(QtCore.QRect(70, 0, 75, 23))
        self.pushBtn_2.setObjectName("pushBtn_2")
        self.pushBtn_2.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(4))
        fbooking.setCentralWidget(self.centralwidget)

        self.retranslateUi(fbooking)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(fbooking)

    def retranslateUi(self, fbooking):
        _translate = QtCore.QCoreApplication.translate
        fbooking.setWindowTitle(_translate("fbooking", "MainWindow"))
        self.label_47.setText(_translate("fbooking", "Enter Your Details"))
        self.label_48.setText(_translate("fbooking", "GENDER:"))
        self.label_49.setText(_translate("fbooking", "ADDRESS:"))
        self.textEdit_2.setHtml(_translate("fbooking", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_50.setText(_translate("fbooking", "ENTER NAME:"))
        self.radioButton.setText(_translate("fbooking", "MALE"))
        self.radioButton_2.setText(_translate("fbooking", "FEMALE"))
        self.label_51.setText(_translate("fbooking", "ADHARCARD NO.:"))
        self.label_52.setText(_translate("fbooking", "CAR COLOUR:"))
        self.label_53.setText(_translate("fbooking", "CAR BRAND:"))
        self.label_54.setText(_translate("fbooking", "CONTACT NO.:"))
        self.label_55.setText(_translate("fbooking", "CAR NO.:"))
        self.label_56.setText(_translate("fbooking", "CAR MODEL:"))
        self.comboBox_2.setItemText(0, _translate("fbooking", "TESLA"))
        self.comboBox_2.setItemText(1, _translate("fbooking", "FERRARI"))
        self.comboBox_2.setItemText(2, _translate("fbooking", "JEEP"))
        self.comboBox_2.setItemText(3, _translate("fbooking", "LANDROVER"))
        self.comboBox_2.setItemText(4, _translate("fbooking", "PORSCHE"))
        self.comboBox_2.setItemText(5, _translate("fbooking", "HYUNDAI"))
        self.comboBox_2.setItemText(6, _translate("fbooking", "HONDA"))
        self.comboBox_2.setItemText(7, _translate("fbooking", "SUZUKI"))
        self.comboBox_2.setItemText(8, _translate("fbooking", "BMW"))
        self.comboBox_2.setItemText(9, _translate("fbooking", "AUDI"))
        self.comboBox_2.setItemText(10, _translate("fbooking", "TATA"))
        self.comboBox_2.setItemText(11, _translate("fbooking", "SKODA"))
        self.comboBox_2.setItemText(12, _translate("fbooking", "MERCEDES"))
        self.pushButton.setText(_translate("fbooking", "PROCEED"))
        self.label_5.setText(_translate("fbooking", "Select Hours:"))
        self.comboBox.setItemText(0, _translate("fbooking", "--Select--"))
        self.comboBox.setItemText(1, _translate("fbooking", "1hr"))
        self.comboBox.setItemText(2, _translate("fbooking", "2hr"))
        self.comboBox.setItemText(3, _translate("fbooking", "3hr"))
        self.comboBox.setItemText(4, _translate("fbooking", "4hr"))
        self.comboBox.setItemText(5, _translate("fbooking", "5hr"))
        self.comboBox.setItemText(6, _translate("fbooking", "6hr"))
        self.comboBox.setItemText(7, _translate("fbooking", "7hr"))
        self.comboBox.setItemText(8, _translate("fbooking", "8hr"))
        self.comboBox.setItemText(9, _translate("fbooking", "9hr"))
        self.comboBox.setItemText(10, _translate("fbooking", "10hr"))
        self.comboBox.setItemText(11, _translate("fbooking", "11hr"))
        self.comboBox.setItemText(12, _translate("fbooking", "12hr"))
        self.pushBtn_6.setText(_translate("fbooking", "NEXT"))
        self.label_2.setText(_translate("fbooking", "SELECT DATE AND TIME"))
        self.label_3.setText(_translate("fbooking", "DATE:"))
        self.label_4.setText(_translate("fbooking", "Start Time:"))
        self.pushBtn_12.setText(_translate("fbooking", "⬅️"))
        self.pushButton_4.setText(_translate("fbooking", "a2"))
        self.pushButton_8.setText(_translate("fbooking", "b3"))
        self.pushButton_2.setText(_translate("fbooking", "b1"))
        self.pushButton_1.setText(_translate("fbooking", "a1"))
        self.pushButton_14.setText(_translate("fbooking", "b5"))
        self.pushButton_12.setText(_translate("fbooking", "c4"))
        self.label_20.setText(_translate("fbooking", " SELECT YOUR SLOT"))
        self.pushButton_5.setText(_translate("fbooking", "b2"))
        self.pushButton_13.setText(_translate("fbooking", "a5"))
        self.pushBtn_7.setText(_translate("fbooking", "⬅️"))
        self.pushButton_15.setText(_translate("fbooking", "c5"))
        self.pushButton_7.setText(_translate("fbooking", "a3"))
        self.pushButton_11.setText(_translate("fbooking", "b4"))
        self.pushButton_10.setText(_translate("fbooking", "a4"))
        self.pushBtn_8.setText(_translate("fbooking", "BOOK NOW"))
        self.pushButton_9.setText(_translate("fbooking", "c3"))
        self.pushButton_3.setText(_translate("fbooking", "c1"))
        self.pushButton_6.setText(_translate("fbooking", "c2"))
        self.label_12.setText(_translate("fbooking", "Bookingid:"))
        self.label_16.setText(_translate("fbooking", "3"))
        self.label_7.setText(_translate("fbooking", "Car number:"))
        self.label_9.setText(_translate("fbooking", "Car Brand:"))
        self.pushBtn_9.setText(_translate("fbooking", "PayBill"))
        self.label_13.setText(_translate("fbooking", "₹30"))
        #self.label_19.setText(_translate("fbooking", "3"))
        self.label_18.setText(_translate("fbooking", ""))
        self.label_15.setText(_translate("fbooking", "2"))
        self.label_10.setText(_translate("fbooking", "Adhar No:"))
        self.label_8.setText(_translate("fbooking", "User Name:"))
        self.label_17.setText(_translate("fbooking", "3"))
        self.label_11.setText(_translate("fbooking", "Total Cost"))
        #self.label_14.setText(_translate("fbooking", "1"))
        self.pushBtn_10.setText(_translate("fbooking", "⬅️"))
        self.label_21.setText(_translate("fbooking", "Slot number:"))
        self.label_25.setText(_translate("fbooking", "Slot number:"))
        self.label_26.setText(_translate("fbooking", "Cost Per Hour:"))
        self.label_27.setText(_translate("fbooking", "3"))
        self.label_28.setText(_translate("fbooking", "3"))
        self.label_29.setText(_translate("fbooking", "User Name:"))
        self.label_30.setText(_translate("fbooking", "START TIME:"))
        self.label_31.setText(_translate("fbooking", "1"))
        self.label_32.setText(_translate("fbooking", "2"))
        self.label_33.setText(_translate("fbooking", "3"))
        self.label_34.setText(_translate("fbooking", "Total Cost:"))
        self.label_35.setText(_translate("fbooking", "3"))
        self.label_36.setText(_translate("fbooking", "Car number:"))
        self.label_37.setText(_translate("fbooking", "END TIME:"))
        self.label_38.setText(_translate("fbooking", "₹30"))
        self.label_39.setText(_translate("fbooking", "3"))
        self.label_40.setText(_translate("fbooking", "#Token_Number:"))
        self.label_41.setText(_translate("fbooking", "Your Query:"))
        self.label_23.setText(_translate("fbooking", "Mail Us At                 :             CarParking@siesgst.ac.in"))
        self.label_42.setText(_translate("fbooking", "Contact Number       :             1234567890"))
        self.pushBtn_11.setText(_translate("fbooking", "Submit"))
        self.label_43.setText(_translate("fbooking", "Ritvij Iyer                    :             117A3014"))
        self.label_44.setText(_translate("fbooking", "Rajesh  Jethwa            :             117A3018"))
        self.label_45.setText(_translate("fbooking", "Shreyas Jaiswal           :             117A3017"))
        self.label_46.setText(_translate("fbooking", "MANAGED & CREATED BY:-"))
        self.pushBtn_1.setText(_translate("fbooking", "Book"))
        self.pushBtn_3.setText(_translate("fbooking", "Contact Us"))
        self.pushBtn_4.setText(_translate("fbooking", "About Us"))
        self.pushBtn_5.setText(_translate("fbooking", "Logout"))
        self.pushBtn_2.setText(_translate("fbooking", "View Booking"))


if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    fbooking = QtWidgets.QMainWindow()
    ui = Ui_fbooking()
    ui.setupUi(fbooking)
    fbooking.show()
    sys.exit(app.exec_())

