from gtts import gTTS
import os
from playsound import playsound
import smtplib
from PyQt5.QtWidgets import QInputDialog, QLineEdit, QDialog
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from F1booking import Ui_fbooking
import pymysql
import sys
import random
class Ui_Flogin(object):
    def __init__(self):
        playsound('C:/Users/ritvij/Desktop/hello3.mp3')

        self.mail=""
        self.username1=""
        self.password1=""
        self.username=""
        self.emailid=""
        self.U_username=""
        self.U_mail=""
        self.dell=""
        pass
    def messagebox111(self, title, message):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()
        playsound('C:/Users/ritvij/Desktop/hello2.mp3')
        self.Dtable()
    def Dtable(self):
        conn = pymysql.connect(host="localhost", user="root", password="123456", db="customer")
        cur = conn.cursor()
        query = "select * from bookingdetails "
        cur.execute(query)
        data = cur.fetchall()
        self.tableWidget.setRowCount(0)
        for row_number, row_data in enumerate(data):
            self.tableWidget.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.tableWidget.setItem(row_number,column_number, QtWidgets.QTableWidgetItem(str(data)))

        conn.close()
        self.stackedWidget.setCurrentIndex(3)

    def deluserbook(self):
        self.dell=self.lineEdit_7.text()
        if self.dell=="":
            self.warning("Alert!","Field Empty")
        else:
            conn = pymysql.connect(host="localhost", user="root", password="123456", db="customer")
            cur = conn.cursor()
            query = "Delete from bookingdetails where Bookingid=%s"
            cur.execute(query, (self.dell))
            conn.commit()
            self.mess("","Booking Cancellation Sucessful")

    def mess(self, title, message):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()
    def messagebox1111(self, title, message):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()
        conn=pymysql.connect(host="localhost", user="root", password="123456", db="customer")
        cur=conn.cursor()
        query = "select mail from login where username=%s"
        cur.execute(query, (self.username))
        data = cur.fetchall()
        print(data[0][0])
        self.emailid=data[0][0]
        self.lineEdit_1.setText("")
        self.lineEdit_2.setText("")
        self.openwindow()




    def login1(self):

        self.username = self.lineEdit_1.text()
        password = self.lineEdit_2.text()

        conn = pymysql.connect(host="localhost", user="root", password="123456", db="customer")
        cur = conn.cursor()
        query = "select * from login where username=%s and password=%s"
        data = cur.execute(query, (self.username, password))
        if (self.username == "admin" and password == "admin"):

            self.messagebox111("Successful", "LOGIN:Successful")
        elif (len(cur.fetchall()) > 0):

            self.messagebox1111("Successful", "LOGIN:Successful")

        else:
            self.warning("Alert!", "CHECK USERNAME OR PASSWORD")



    def openwindow(self,):
        r1=random.randint(1,100000000)

        file1 = str("hello" + str(r1) + ".mp3")
        speech = gTTS(f"Welcome, {self.username}", 'en')
        speech.save(file1)
        playsound(file1)
        os.remove(file1)

        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_fbooking(self.emailid,self.username)
        self.ui.setupUi(self.window)
        self.window.show()


    def messagebox(self, title, message):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()
        self.stackedWidget.setCurrentIndex(1)
        s= smtplib.SMTP('smtp.gmail.com',587)
        s.starttls()
        s.login("carparkingsiesgst@gmail.com","siesgst123")
        message= f"ThankYou '{self.username1}' for registering in our car parking system.\nYour password is '{self.password1}'"
        s.sendmail("carparkingsiesgst@gmail.com",self.mail,message)
        s.quit()
        playsound('C:/Users/ritvij/Desktop/hello1.mp3')




        #self.openwindow()
        #self.oplog()

    def warning(self, title, message):

        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)

        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)

        mess.exec_()


    def signup(self):
        self.username1 = self.lineEdit_4.text()
        fpassword = self.lineEdit_9.text()
        self.password1 = self.lineEdit_8.text()
        self.mail = self.lineEdit_6.text()
        if (self.username1 == ""):

            self.warning("Alert!", "FIELDS CANNOT BE EMPTY!.")

        elif (self.mail == ""):
            self.warning("Alert!", "FIELDS CANNOT BE EMPTY!.")
        elif (fpassword == self.password1):


            conn = pymysql.connect(host="localhost", user="root", port=3306, password="123456", db="customer")
            cur = conn.cursor()
            query = "insert into login(username,password,mail)values(%s,%s,%s)"
            data = cur.execute(query, (self.username1, self.password1,self.mail))
            conn.commit()
            if (data):
                self.messagebox("congrats", "successful")

        else:
            self.warning("Alert!", "Both password does not match")



    def setup1(self, Flogin):
        Flogin.setObjectName("Flogin")
        Flogin.resize(750, 439)
        self.stackedWidget = QtWidgets.QStackedWidget(Flogin)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 751, 441))
        self.stackedWidget.setObjectName("stackedWidget")
        #PAGE 1
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(0, 0, 751, 441))
        self.label.setText("")
        self.label.setPixmap(QPixmap("park11.png"))
        self.label.setObjectName("label")

        self.pushBtn_1 = QtWidgets.QPushButton(self.page)
        self.pushBtn_1.setGeometry(QtCore.QRect(280, 360, 191, 51))
        self.pushBtn_1.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(1))

        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushBtn_1.setFont(font)
        self.pushBtn_1.setObjectName("pushBtn_1")

        self.stackedWidget.addWidget(self.page)
        #PAGE 2
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(270, 40, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Playbill")
        font.setPointSize(55)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setGeometry(QtCore.QRect(80, 230, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(80, 140, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(300, 240, 171, 21))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_1.setGeometry(QtCore.QRect(300, 150, 171, 21))
        self.lineEdit_1.setText("")
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setGeometry(QtCore.QRect(200, 380, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushBtn_2 = QtWidgets.QPushButton(self.page_2)
        self.pushBtn_2.setGeometry(QtCore.QRect(310, 300, 141, 41))
        self.pushBtn_2.setObjectName("pushBtn_2")
        self.pushBtn_2.clicked.connect(self.login1)
        self.label_12 = QtWidgets.QLabel(self.page_2)
        self.label_12.setGeometry(QtCore.QRect(0, 0, 751, 441))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setText("")
        self.label_12.setPixmap(QPixmap("car3.jpg"))
        self.label_12.setObjectName("label_12")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.page_2)
        self.commandLinkButton.setGeometry(QtCore.QRect(330, 370, 241, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.commandLinkButton.clicked.connect(lambda : self.stackedWidget.setCurrentIndex(2))

        self.label_12.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_1.raise_()
        self.label_5.raise_()
        self.pushBtn_2.raise_()
        self.commandLinkButton.raise_()
        self.stackedWidget.addWidget(self.page_2)
        #page 3
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setGeometry(QtCore.QRect(50, 220, 131, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_6.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushBtn_4 = QtWidgets.QPushButton(self.page_3)
        self.pushBtn_4.setGeometry(QtCore.QRect(300, 360, 161, 41))
        self.pushBtn_4.setObjectName("pushBtn_4")
        self.pushBtn_4.clicked.connect(self.signup)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_8.setGeometry(QtCore.QRect(300, 220, 171, 31))
        self.lineEdit_8.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_7 = QtWidgets.QLabel(self.page_3)
        self.label_7.setGeometry(QtCore.QRect(50, 90, 211, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_7.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_11 = QtWidgets.QLabel(self.page_3)
        self.label_11.setGeometry(QtCore.QRect(240, 20, 301, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_11.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_4.setGeometry(QtCore.QRect(300, 90, 171, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_8 = QtWidgets.QLabel(self.page_3)
        self.label_8.setGeometry(QtCore.QRect(50, 290, 251, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_8.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_9.setGeometry(QtCore.QRect(300, 290, 171, 31))
        self.lineEdit_9.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_9 = QtWidgets.QLabel(self.page_3)
        self.label_9.setGeometry(QtCore.QRect(50, 150, 111, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_9.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_6.setGeometry(QtCore.QRect(300, 150, 171, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_10 = QtWidgets.QLabel(self.page_3)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 751, 441))
        self.label_10.setText("")
        self.label_10.setPixmap(QPixmap("car11.jpg"))
        self.label_10.setObjectName("label_10")
        self.pushBtn_3 = QtWidgets.QPushButton(self.page_3)
        self.pushBtn_3.setGeometry(QtCore.QRect(670, 0, 81, 41))
        self.pushBtn_3.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(1))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.pushBtn_3.setFont(font)
        self.pushBtn_3.setObjectName("pushBtn_3")
        self.label_10.raise_()
        self.label_6.raise_()
        self.pushBtn_4.raise_()
        self.lineEdit_8.raise_()
        self.label_7.raise_()
        self.label_11.raise_()
        self.lineEdit_4.raise_()
        self.label_8.raise_()
        self.lineEdit_9.raise_()
        self.label_9.raise_()
        self.lineEdit_6.raise_()
        self.pushBtn_3.raise_()
        self.stackedWidget.addWidget(self.page_3)
        #PAGE 4
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_13 = QtWidgets.QLabel(self.page_4)
        self.label_13.setGeometry(QtCore.QRect(0, 0, 751, 431))
        self.label_13.setText("")
        self.label_13.setPixmap(QPixmap("blue1.png"))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.page_4)
        self.label_14.setGeometry(QtCore.QRect(260, 10, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Playbill")
        font.setPointSize(36)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.tableWidget = QtWidgets.QTableWidget(self.page_4)
        self.tableWidget.setGeometry(QtCore.QRect(0, 80, 751, 361))
        self.tableWidget.setRowCount(20)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(13)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)





        self.pushBtn_5 = QtWidgets.QPushButton(self.page_4)
        self.pushBtn_5.setGeometry(QtCore.QRect(0, 50, 161, 23))
        self.pushBtn_5.setObjectName("pushBtn_5")
        self.pushBtn_5.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(4))
        self.pushBtn_0 = QtWidgets.QPushButton(self.page_4)
        self.pushBtn_0.setGeometry(QtCore.QRect(670, 0, 81, 41))
        self.pushBtn_0.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(1))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushBtn_0.setFont(font)
        self.pushBtn_0.setObjectName("pushBtn_0")
        self.pushBtn_0.raise_()
        #PAGE 5
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_15 = QtWidgets.QLabel(self.page_5)
        self.label_15.setGeometry(QtCore.QRect(0, 0, 751, 441))
        self.label_15.setText("")
        self.label_15.setPixmap(QPixmap("blue1.png"))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.page_5)
        self.label_16.setGeometry(QtCore.QRect(260, 10, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Playbill")
        font.setPointSize(36)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.pushBtn_6 = QtWidgets.QPushButton(self.page_5)
        self.pushBtn_6.setGeometry(QtCore.QRect(0, 50, 161, 23))
        self.pushBtn_6.setObjectName("pushBtn_6")
        self.pushBtn_6.clicked.connect(self.Dtable)

        self.label_17 = QtWidgets.QLabel(self.page_5)
        self.label_17.setGeometry(QtCore.QRect(30, 140, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_7.setGeometry(QtCore.QRect(360, 160, 251, 21))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushBtn_7 = QtWidgets.QPushButton(self.page_5)
        self.pushBtn_7.setGeometry(QtCore.QRect(290, 310, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushBtn_7.setFont(font)
        self.pushBtn_7.setObjectName("pushBtn_7")
        self.pushBtn_7.clicked.connect(self.deluserbook)
        self.pushBtn_00 = QtWidgets.QPushButton(self.page_5)
        self.pushBtn_00.setGeometry(QtCore.QRect(670, 0, 81, 41))
        self.pushBtn_00.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(1))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushBtn_00.setFont(font)
        self.pushBtn_00.setObjectName("pushBtn_0")
        self.pushBtn_00.raise_()
        self.stackedWidget.addWidget(self.page_5)

        self.retranslateUi(Flogin)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Flogin)

    def retranslateUi(self, Flogin):
        _translate = QtCore.QCoreApplication.translate
        Flogin.setWindowTitle(_translate("Flogin", "Form"))
        self.pushBtn_1.setText(_translate("Flogin", "Welcome"))
        self.label_2.setText(_translate("Flogin", "🔒LOGIN"))
        self.label_4.setText(_translate("Flogin", "Password:"))
        self.label_3.setText(_translate("Flogin", "Username:"))
        self.label_5.setText(_translate("Flogin", "Not Register?"))
        self.pushBtn_2.setText(_translate("Flogin", "Login"))
        self.commandLinkButton.setText(_translate("Flogin", "CLICK HERE TO REGISTER"))
        self.label_6.setText(_translate("Flogin", "PASSWORD:"))
        self.pushBtn_4.setText(_translate("Flogin", "Register"))
        self.label_7.setText(_translate("Flogin", "ENTER USERNAME:"))
        self.label_11.setText(_translate("Flogin", "REGISTRATION"))
        self.label_8.setText(_translate("Flogin", "RE-ENTERPASSWORD:"))
        self.label_9.setText(_translate("Flogin", "EMAIL-ID:"))
        self.pushBtn_3.setText(_translate("Flogin", "⬅️"))
        self.pushBtn_0.setText(_translate("Flogin", "Logout"))
        self.pushBtn_00.setText(_translate("Flogin", "Logout"))
        self.label_14.setText(_translate("Flogin", "WELCOME, ADMIN"))
        self.pushBtn_5.setText(_translate("Flogin", "CANCLE CUSTOMER BOOKING"))
        self.label_16.setText(_translate("Flogin", "WELCOME, ADMIN"))
        self.pushBtn_6.setText(_translate("Flogin", "VIEW CUSTOMER BOOKING"))
        self.label_17.setText(_translate("Flogin", "Enter Customer Booking ID :"))
        self.pushBtn_7.setText(_translate("Flogin", "OK"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Flogin", "Username"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Flogin", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Flogin", "BookingID"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Flogin", "Address"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Flogin", "Gender"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Flogin", "Adharcard No."))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Flogin", "Contact"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Flogin", "CarNo"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Flogin", "CarBrand"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Flogin", "CarModel"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("Flogin", "CarColour"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("Flogin", "SlotNo."))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("Flogin", "Date"))
        item = self.tableWidget.horizontalHeaderItem(13)


if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    Flogin = QtWidgets.QWidget()
    ui = Ui_Flogin()
    ui.setup1(Flogin)
    Flogin.show()
    sys.exit(app.exec_())

