

from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql
from login import *
class Ui_T_login(object):

    def openwindow(self):
        self.log = QtWidgets.QMainWindow()
        self.ui = Ui_log()
        self.ui.setup1(self.log)
        self.log.show()

    def messagebox(self, title, message):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()

        self.openwindow()
    def warning(self, title, message):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()

    def signup(self):
        username=self.lineEdit.text()
        fpassword=self.lineEdit_2.text()
        password=self.lineEdit_3.text()
        if(username==""):
            self.warning("Alert!", "FIELDS CANNOT BE EMPTY!.")
        elif(fpassword==password):
            conn=pymysql.connect(host="localhost",user="root",port=3306,password="123456",db="customer")
            cur =conn.cursor()
            query= "insert into login(username,password)values(%s,%s)"
            data = cur.execute(query, (username, password))
            conn.commit()
            if(data):
                self.messagebox("congrats","successful")
        else:
            self.warning("Alert!","Both password does not match")

    def setup2(self, T_login):
        T_login.setObjectName("T_login")
        T_login.resize(570, 372)
        self.label = QtWidgets.QLabel(T_login)
        self.label.setGeometry(QtCore.QRect(0, 0, 571, 371))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("blue1.jpg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(T_login)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 211, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(T_login)
        self.label_3.setGeometry(QtCore.QRect(20, 160, 211, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(T_login)
        self.label_4.setGeometry(QtCore.QRect(20, 240, 251, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_4.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(T_login)
        self.lineEdit.setGeometry(QtCore.QRect(330, 80, 171, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(T_login)
        self.lineEdit_2.setGeometry(QtCore.QRect(330, 160, 171, 31))
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(T_login)
        self.lineEdit_3.setGeometry(QtCore.QRect(330, 240, 171, 31))
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(T_login)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 91, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_5.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(T_login)
        self.pushButton.setGeometry(QtCore.QRect(220, 320, 121, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.signup)
        self.label_11 = QtWidgets.QLabel(T_login)
        self.label_11.setGeometry(QtCore.QRect(140, 10, 301, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_11.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")

        self.retranslateUi(T_login)
        QtCore.QMetaObject.connectSlotsByName(T_login)

    def retranslateUi(self, T_login):
        _translate = QtCore.QCoreApplication.translate
        T_login.setWindowTitle(_translate("T_login", "Form"))
        self.label_2.setText(_translate("T_login", "ENTER USERNAME:"))
        self.label_3.setText(_translate("T_login", "PASSWORD:"))
        self.label_4.setText(_translate("T_login", "RE-ENTERPASSWORD:"))
        self.label_5.setText(_translate("T_login", "STEP 1:"))
        self.pushButton.setText(_translate("T_login", "SAVE"))
        self.label_11.setText(_translate("T_login", "REGISTRATION"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    T_login = QtWidgets.QWidget()
    ui = Ui_T_login()
    ui.setup2(T_login)
    T_login.show()
    sys.exit(app.exec_())

